let SAMPLE = {
  "location": {
    "name": "Gatineau",
    "region": "Quebec",
    "country": "Canada",
    "lat": 45.48,
    "lon": -75.65,
    "tz_id": "America/Toronto",
    "localtime_epoch": 1665328302,
    "localtime": "2022-10-09 11:11"
  },
  "current": {
    "last_updated_epoch": 1665327600,
    "last_updated": "2022-10-09 11:00",
    "temp_c": 8,
    "temp_f": 46.4,
    "is_day": 1,
    "condition": {
      "text": "Partly cloudy",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
      "code": 1003
    },
    "wind_mph": 10.5,
    "wind_kph": 16.9,
    "wind_degree": 290,
    "wind_dir": "WNW",
    "pressure_mb": 1014,
    "pressure_in": 29.94,
    "precip_mm": 0,
    "precip_in": 0,
    "humidity": 87,
    "cloud": 75,
    "feelslike_c": 4.7,
    "feelslike_f": 40.5,
    "vis_km": 24,
    "vis_miles": 14,
    "uv": 3,
    "gust_mph": 15.2,
    "gust_kph": 24.5
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2022-10-09",
        "date_epoch": 1665273600,
        "day": {
          "maxtemp_c": 13.3,
          "maxtemp_f": 55.9,
          "mintemp_c": 5.3,
          "mintemp_f": 41.5,
          "avgtemp_c": 8.8,
          "avgtemp_f": 47.8,
          "maxwind_mph": 14.8,
          "maxwind_kph": 23.8,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "avgvis_km": 9.7,
          "avgvis_miles": 6,
          "avghumidity": 65,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
          },
          "uv": 3
        },
        "astro": {
          "sunrise": "07:12 AM",
          "sunset": "06:28 PM",
          "moonrise": "06:38 PM",
          "moonset": "06:40 AM",
          "moon_phase": "Waxing Gibbous",
          "moon_illumination": "95"
        },
        "hour": [
          {
            "time_epoch": 1665288000,
            "time": "2022-10-09 00:00",
            "temp_c": 8,
            "temp_f": 46.4,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 12.1,
            "wind_kph": 19.4,
            "wind_degree": 236,
            "wind_dir": "WSW",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 69,
            "cloud": 88,
            "feelslike_c": 5.6,
            "feelslike_f": 42.1,
            "windchill_c": 5.6,
            "windchill_f": 42.1,
            "heatindex_c": 8,
            "heatindex_f": 46.4,
            "dewpoint_c": 2.7,
            "dewpoint_f": 36.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 18.3,
            "gust_kph": 29.5,
            "uv": 1
          },
          {
            "time_epoch": 1665291600,
            "time": "2022-10-09 01:00",
            "temp_c": 8,
            "temp_f": 46.4,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 225,
            "wind_dir": "SW",
            "pressure_mb": 1013,
            "pressure_in": 29.92,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 69,
            "cloud": 87,
            "feelslike_c": 5.6,
            "feelslike_f": 42.1,
            "windchill_c": 5.6,
            "windchill_f": 42.1,
            "heatindex_c": 8,
            "heatindex_f": 46.4,
            "dewpoint_c": 2.6,
            "dewpoint_f": 36.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.8,
            "gust_kph": 27,
            "uv": 1
          },
          {
            "time_epoch": 1665295200,
            "time": "2022-10-09 02:00",
            "temp_c": 7.8,
            "temp_f": 46,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 11.6,
            "wind_kph": 18.7,
            "wind_degree": 225,
            "wind_dir": "SW",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 69,
            "cloud": 100,
            "feelslike_c": 5.3,
            "feelslike_f": 41.5,
            "windchill_c": 5.3,
            "windchill_f": 41.5,
            "heatindex_c": 7.8,
            "heatindex_f": 46,
            "dewpoint_c": 2.4,
            "dewpoint_f": 36.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.7,
            "gust_kph": 28.4,
            "uv": 1
          },
          {
            "time_epoch": 1665298800,
            "time": "2022-10-09 03:00",
            "temp_c": 7.6,
            "temp_f": 45.7,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 11.2,
            "wind_kph": 18,
            "wind_degree": 232,
            "wind_dir": "SW",
            "pressure_mb": 1013,
            "pressure_in": 29.9,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 69,
            "cloud": 100,
            "feelslike_c": 4.8,
            "feelslike_f": 40.6,
            "windchill_c": 4.8,
            "windchill_f": 40.6,
            "heatindex_c": 7.6,
            "heatindex_f": 45.7,
            "dewpoint_c": 2.4,
            "dewpoint_f": 36.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.6,
            "gust_kph": 26.6,
            "uv": 1
          },
          {
            "time_epoch": 1665302400,
            "time": "2022-10-09 04:00",
            "temp_c": 7.1,
            "temp_f": 44.8,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 10.1,
            "wind_kph": 16.2,
            "wind_degree": 227,
            "wind_dir": "SW",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 75,
            "cloud": 100,
            "feelslike_c": 3.9,
            "feelslike_f": 39,
            "windchill_c": 3.9,
            "windchill_f": 39,
            "heatindex_c": 7.1,
            "heatindex_f": 44.8,
            "dewpoint_c": 3,
            "dewpoint_f": 37.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.2,
            "gust_kph": 24.5,
            "uv": 1
          },
          {
            "time_epoch": 1665306000,
            "time": "2022-10-09 05:00",
            "temp_c": 6.9,
            "temp_f": 44.4,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 222,
            "wind_dir": "SW",
            "pressure_mb": 1012,
            "pressure_in": 29.88,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 81,
            "cloud": 100,
            "feelslike_c": 3.7,
            "feelslike_f": 38.7,
            "windchill_c": 3.7,
            "windchill_f": 38.7,
            "heatindex_c": 6.9,
            "heatindex_f": 44.4,
            "dewpoint_c": 3.9,
            "dewpoint_f": 39,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.3,
            "gust_kph": 26.3,
            "uv": 1
          },
          {
            "time_epoch": 1665309600,
            "time": "2022-10-09 06:00",
            "temp_c": 6.4,
            "temp_f": 43.5,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 11,
            "wind_kph": 17.6,
            "wind_degree": 224,
            "wind_dir": "SW",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 91,
            "cloud": 100,
            "feelslike_c": 3.3,
            "feelslike_f": 37.9,
            "windchill_c": 3.3,
            "windchill_f": 37.9,
            "heatindex_c": 6.4,
            "heatindex_f": 43.5,
            "dewpoint_c": 5,
            "dewpoint_f": 41,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17,
            "gust_kph": 27.4,
            "uv": 1
          },
          {
            "time_epoch": 1665313200,
            "time": "2022-10-09 07:00",
            "temp_c": 6.5,
            "temp_f": 43.7,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 11.2,
            "wind_kph": 18,
            "wind_degree": 231,
            "wind_dir": "SW",
            "pressure_mb": 1013,
            "pressure_in": 29.9,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 92,
            "cloud": 100,
            "feelslike_c": 3.7,
            "feelslike_f": 38.7,
            "windchill_c": 3.7,
            "windchill_f": 38.7,
            "heatindex_c": 6.5,
            "heatindex_f": 43.7,
            "dewpoint_c": 5.3,
            "dewpoint_f": 41.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.8,
            "gust_kph": 27,
            "uv": 1
          },
          {
            "time_epoch": 1665316800,
            "time": "2022-10-09 08:00",
            "temp_c": 6.8,
            "temp_f": 44.2,
            "is_day": 1,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 11.6,
            "wind_kph": 18.7,
            "wind_degree": 261,
            "wind_dir": "W",
            "pressure_mb": 1013,
            "pressure_in": 29.9,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 94,
            "cloud": 98,
            "feelslike_c": 4.3,
            "feelslike_f": 39.7,
            "windchill_c": 4.3,
            "windchill_f": 39.7,
            "heatindex_c": 6.8,
            "heatindex_f": 44.2,
            "dewpoint_c": 5.9,
            "dewpoint_f": 42.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2,
            "vis_miles": 1,
            "gust_mph": 16.6,
            "gust_kph": 26.6,
            "uv": 2
          },
          {
            "time_epoch": 1665320400,
            "time": "2022-10-09 09:00",
            "temp_c": 8.8,
            "temp_f": 47.8,
            "is_day": 1,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 11.2,
            "wind_kph": 18,
            "wind_degree": 261,
            "wind_dir": "W",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 65,
            "feelslike_c": 6.3,
            "feelslike_f": 43.3,
            "windchill_c": 6.3,
            "windchill_f": 43.3,
            "heatindex_c": 8.8,
            "heatindex_f": 47.8,
            "dewpoint_c": 5.5,
            "dewpoint_f": 41.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.2,
            "gust_kph": 24.5,
            "uv": 2
          },
          {
            "time_epoch": 1665324000,
            "time": "2022-10-09 10:00",
            "temp_c": 9.6,
            "temp_f": 49.3,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 13.2,
            "wind_kph": 21.2,
            "wind_degree": 281,
            "wind_dir": "WNW",
            "pressure_mb": 1013,
            "pressure_in": 29.93,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 75,
            "cloud": 40,
            "feelslike_c": 6.9,
            "feelslike_f": 44.4,
            "windchill_c": 6.9,
            "windchill_f": 44.4,
            "heatindex_c": 9.6,
            "heatindex_f": 49.3,
            "dewpoint_c": 5.4,
            "dewpoint_f": 41.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.2,
            "gust_kph": 24.5,
            "uv": 3
          },
          {
            "time_epoch": 1665327600,
            "time": "2022-10-09 11:00",
            "temp_c": 10.7,
            "temp_f": 51.3,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 14.3,
            "wind_kph": 23,
            "wind_degree": 299,
            "wind_dir": "WNW",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 66,
            "cloud": 26,
            "feelslike_c": 8.1,
            "feelslike_f": 46.6,
            "windchill_c": 8.1,
            "windchill_f": 46.6,
            "heatindex_c": 10.7,
            "heatindex_f": 51.3,
            "dewpoint_c": 4.6,
            "dewpoint_f": 40.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.6,
            "gust_kph": 26.6,
            "uv": 4
          },
          {
            "time_epoch": 1665331200,
            "time": "2022-10-09 12:00",
            "temp_c": 12,
            "temp_f": 53.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 14.8,
            "wind_kph": 23.8,
            "wind_degree": 299,
            "wind_dir": "WNW",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 57,
            "cloud": 7,
            "feelslike_c": 9.7,
            "feelslike_f": 49.5,
            "windchill_c": 9.7,
            "windchill_f": 49.5,
            "heatindex_c": 12,
            "heatindex_f": 53.6,
            "dewpoint_c": 3.7,
            "dewpoint_f": 38.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17,
            "gust_kph": 27.4,
            "uv": 4
          },
          {
            "time_epoch": 1665334800,
            "time": "2022-10-09 13:00",
            "temp_c": 11.7,
            "temp_f": 53.1,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 14.5,
            "wind_kph": 23.4,
            "wind_degree": 297,
            "wind_dir": "WNW",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 51,
            "cloud": 27,
            "feelslike_c": 9.3,
            "feelslike_f": 48.7,
            "windchill_c": 9.3,
            "windchill_f": 48.7,
            "heatindex_c": 11.7,
            "heatindex_f": 53.1,
            "dewpoint_c": 1.9,
            "dewpoint_f": 35.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.8,
            "gust_kph": 27,
            "uv": 4
          },
          {
            "time_epoch": 1665338400,
            "time": "2022-10-09 14:00",
            "temp_c": 13.3,
            "temp_f": 55.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 13,
            "wind_kph": 20.9,
            "wind_degree": 296,
            "wind_dir": "WNW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 46,
            "cloud": 0,
            "feelslike_c": 11.4,
            "feelslike_f": 52.5,
            "windchill_c": 11.4,
            "windchill_f": 52.5,
            "heatindex_c": 13.3,
            "heatindex_f": 55.9,
            "dewpoint_c": 2.1,
            "dewpoint_f": 35.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15,
            "gust_kph": 24.1,
            "uv": 4
          },
          {
            "time_epoch": 1665342000,
            "time": "2022-10-09 15:00",
            "temp_c": 11.1,
            "temp_f": 52,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 12.1,
            "wind_kph": 19.4,
            "wind_degree": 296,
            "wind_dir": "WNW",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 45,
            "cloud": 60,
            "feelslike_c": 8.8,
            "feelslike_f": 47.8,
            "windchill_c": 8.8,
            "windchill_f": 47.8,
            "heatindex_c": 11.1,
            "heatindex_f": 52,
            "dewpoint_c": -0.2,
            "dewpoint_f": 31.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.9,
            "gust_kph": 22.3,
            "uv": 4
          },
          {
            "time_epoch": 1665345600,
            "time": "2022-10-09 16:00",
            "temp_c": 11.2,
            "temp_f": 52.2,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 11,
            "wind_kph": 17.6,
            "wind_degree": 295,
            "wind_dir": "WNW",
            "pressure_mb": 1017,
            "pressure_in": 30.04,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 45,
            "cloud": 31,
            "feelslike_c": 9.1,
            "feelslike_f": 48.4,
            "windchill_c": 9.1,
            "windchill_f": 48.4,
            "heatindex_c": 11.2,
            "heatindex_f": 52.2,
            "dewpoint_c": -0.4,
            "dewpoint_f": 31.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.5,
            "gust_kph": 20.2,
            "uv": 4
          },
          {
            "time_epoch": 1665349200,
            "time": "2022-10-09 17:00",
            "temp_c": 12.7,
            "temp_f": 54.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 301,
            "wind_dir": "WNW",
            "pressure_mb": 1018,
            "pressure_in": 30.05,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 44,
            "cloud": 0,
            "feelslike_c": 11.4,
            "feelslike_f": 52.5,
            "windchill_c": 11.4,
            "windchill_f": 52.5,
            "heatindex_c": 12.7,
            "heatindex_f": 54.9,
            "dewpoint_c": 0.8,
            "dewpoint_f": 33.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 4
          },
          {
            "time_epoch": 1665352800,
            "time": "2022-10-09 18:00",
            "temp_c": 9,
            "temp_f": 48.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 310,
            "wind_dir": "NW",
            "pressure_mb": 1019,
            "pressure_in": 30.08,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 49,
            "cloud": 11,
            "feelslike_c": 7.4,
            "feelslike_f": 45.3,
            "windchill_c": 7.4,
            "windchill_f": 45.3,
            "heatindex_c": 9,
            "heatindex_f": 48.2,
            "dewpoint_c": -1.2,
            "dewpoint_f": 29.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.7,
            "gust_kph": 14,
            "uv": 3
          },
          {
            "time_epoch": 1665356400,
            "time": "2022-10-09 19:00",
            "temp_c": 10.3,
            "temp_f": 50.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 334,
            "wind_dir": "NNW",
            "pressure_mb": 1019,
            "pressure_in": 30.1,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 53,
            "cloud": 1,
            "feelslike_c": 9.6,
            "feelslike_f": 49.3,
            "windchill_c": 9.6,
            "windchill_f": 49.3,
            "heatindex_c": 10.3,
            "heatindex_f": 50.5,
            "dewpoint_c": 1.2,
            "dewpoint_f": 34.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.8,
            "gust_kph": 15.8,
            "uv": 1
          },
          {
            "time_epoch": 1665360000,
            "time": "2022-10-09 20:00",
            "temp_c": 7.2,
            "temp_f": 45,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 1,
            "wind_dir": "N",
            "pressure_mb": 1020,
            "pressure_in": 30.11,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 59,
            "cloud": 1,
            "feelslike_c": 6.3,
            "feelslike_f": 43.3,
            "windchill_c": 6.3,
            "windchill_f": 43.3,
            "heatindex_c": 7.2,
            "heatindex_f": 45,
            "dewpoint_c": -0.3,
            "dewpoint_f": 31.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.2,
            "gust_kph": 18,
            "uv": 1
          },
          {
            "time_epoch": 1665363600,
            "time": "2022-10-09 21:00",
            "temp_c": 6.8,
            "temp_f": 44.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 16,
            "wind_dir": "NNE",
            "pressure_mb": 1020,
            "pressure_in": 30.11,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 57,
            "cloud": 0,
            "feelslike_c": 6.1,
            "feelslike_f": 43,
            "windchill_c": 6.1,
            "windchill_f": 43,
            "heatindex_c": 6.8,
            "heatindex_f": 44.2,
            "dewpoint_c": -1.2,
            "dewpoint_f": 29.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.2,
            "gust_kph": 18,
            "uv": 1
          },
          {
            "time_epoch": 1665367200,
            "time": "2022-10-09 22:00",
            "temp_c": 6.2,
            "temp_f": 43.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 26,
            "wind_dir": "NNE",
            "pressure_mb": 1020,
            "pressure_in": 30.12,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 59,
            "cloud": 10,
            "feelslike_c": 5.7,
            "feelslike_f": 42.3,
            "windchill_c": 5.7,
            "windchill_f": 42.3,
            "heatindex_c": 6.2,
            "heatindex_f": 43.2,
            "dewpoint_c": -1.1,
            "dewpoint_f": 30,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 1
          },
          {
            "time_epoch": 1665370800,
            "time": "2022-10-09 23:00",
            "temp_c": 5.3,
            "temp_f": 41.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 40,
            "wind_dir": "NE",
            "pressure_mb": 1021,
            "pressure_in": 30.14,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 69,
            "cloud": 0,
            "feelslike_c": 4.5,
            "feelslike_f": 40.1,
            "windchill_c": 4.5,
            "windchill_f": 40.1,
            "heatindex_c": 5.3,
            "heatindex_f": 41.5,
            "dewpoint_c": 0.1,
            "dewpoint_f": 32.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.1,
            "gust_kph": 13,
            "uv": 1
          }
        ]
      },
      {
        "date": "2022-10-10",
        "date_epoch": 1665360000,
        "day": {
          "maxtemp_c": 12.7,
          "maxtemp_f": 54.9,
          "mintemp_c": -0.2,
          "mintemp_f": 31.6,
          "avgtemp_c": 5.9,
          "avgtemp_f": 42.7,
          "maxwind_mph": 8.9,
          "maxwind_kph": 14.4,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 60,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 3
        },
        "astro": {
          "sunrise": "07:13 AM",
          "sunset": "06:26 PM",
          "moonrise": "06:58 PM",
          "moonset": "07:54 AM",
          "moon_phase": "Full Moon",
          "moon_illumination": "100"
        },
        "hour": [
          {
            "time_epoch": 1665374400,
            "time": "2022-10-10 00:00",
            "temp_c": 5.6,
            "temp_f": 42.1,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 39,
            "wind_dir": "NE",
            "pressure_mb": 1020,
            "pressure_in": 30.13,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 61,
            "cloud": 94,
            "feelslike_c": 5,
            "feelslike_f": 41,
            "windchill_c": 5,
            "windchill_f": 41,
            "heatindex_c": 5.6,
            "heatindex_f": 42.1,
            "dewpoint_c": -1.2,
            "dewpoint_f": 29.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.5,
            "gust_kph": 13.7,
            "uv": 1
          },
          {
            "time_epoch": 1665378000,
            "time": "2022-10-10 01:00",
            "temp_c": 5.6,
            "temp_f": 42.1,
            "is_day": 0,
            "condition": {
              "text": "Overcast",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 31,
            "wind_dir": "NNE",
            "pressure_mb": 1021,
            "pressure_in": 30.14,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 62,
            "cloud": 94,
            "feelslike_c": 5.4,
            "feelslike_f": 41.7,
            "windchill_c": 5.4,
            "windchill_f": 41.7,
            "heatindex_c": 5.6,
            "heatindex_f": 42.1,
            "dewpoint_c": -1,
            "dewpoint_f": 30.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.7,
            "gust_kph": 14,
            "uv": 1
          },
          {
            "time_epoch": 1665381600,
            "time": "2022-10-10 02:00",
            "temp_c": 3.3,
            "temp_f": 37.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 25,
            "wind_dir": "NNE",
            "pressure_mb": 1021,
            "pressure_in": 30.15,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 75,
            "cloud": 6,
            "feelslike_c": 2.6,
            "feelslike_f": 36.7,
            "windchill_c": 2.6,
            "windchill_f": 36.7,
            "heatindex_c": 3.3,
            "heatindex_f": 37.9,
            "dewpoint_c": -0.6,
            "dewpoint_f": 30.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.3,
            "gust_kph": 13.3,
            "uv": 1
          },
          {
            "time_epoch": 1665385200,
            "time": "2022-10-10 03:00",
            "temp_c": 0.2,
            "temp_f": 32.4,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 10,
            "wind_dir": "N",
            "pressure_mb": 1022,
            "pressure_in": 30.17,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 78,
            "cloud": 44,
            "feelslike_c": -1.8,
            "feelslike_f": 28.8,
            "windchill_c": -1.8,
            "windchill_f": 28.8,
            "heatindex_c": 0.2,
            "heatindex_f": 32.4,
            "dewpoint_c": -3.1,
            "dewpoint_f": 26.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.8,
            "gust_kph": 12.6,
            "uv": 1
          },
          {
            "time_epoch": 1665388800,
            "time": "2022-10-10 04:00",
            "temp_c": 0,
            "temp_f": 32,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 358,
            "wind_dir": "N",
            "pressure_mb": 1022,
            "pressure_in": 30.18,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 79,
            "cloud": 23,
            "feelslike_c": -2.2,
            "feelslike_f": 28,
            "windchill_c": -2.2,
            "windchill_f": 28,
            "heatindex_c": 0,
            "heatindex_f": 32,
            "dewpoint_c": -3.3,
            "dewpoint_f": 26.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.3,
            "gust_kph": 13.3,
            "uv": 1
          },
          {
            "time_epoch": 1665392400,
            "time": "2022-10-10 05:00",
            "temp_c": 3.5,
            "temp_f": 38.3,
            "is_day": 0,
            "condition": {
              "text": "Cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 356,
            "wind_dir": "N",
            "pressure_mb": 1022,
            "pressure_in": 30.17,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 77,
            "feelslike_c": 3,
            "feelslike_f": 37.4,
            "windchill_c": 3,
            "windchill_f": 37.4,
            "heatindex_c": 3.5,
            "heatindex_f": 38.3,
            "dewpoint_c": -0.6,
            "dewpoint_f": 30.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.8,
            "gust_kph": 12.6,
            "uv": 1
          },
          {
            "time_epoch": 1665396000,
            "time": "2022-10-10 06:00",
            "temp_c": 0,
            "temp_f": 32,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 336,
            "wind_dir": "NNW",
            "pressure_mb": 1023,
            "pressure_in": 30.19,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 77,
            "cloud": 11,
            "feelslike_c": -2.2,
            "feelslike_f": 28,
            "windchill_c": -2.2,
            "windchill_f": 28,
            "heatindex_c": 0,
            "heatindex_f": 32,
            "dewpoint_c": -3.5,
            "dewpoint_f": 25.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.1,
            "gust_kph": 13,
            "uv": 1
          },
          {
            "time_epoch": 1665399600,
            "time": "2022-10-10 07:00",
            "temp_c": -0.2,
            "temp_f": 31.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 329,
            "wind_dir": "NNW",
            "pressure_mb": 1023,
            "pressure_in": 30.21,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 79,
            "cloud": 6,
            "feelslike_c": -2.8,
            "feelslike_f": 27,
            "windchill_c": -2.8,
            "windchill_f": 27,
            "heatindex_c": -0.2,
            "heatindex_f": 31.6,
            "dewpoint_c": -3.4,
            "dewpoint_f": 25.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.4,
            "gust_kph": 15.1,
            "uv": 1
          },
          {
            "time_epoch": 1665403200,
            "time": "2022-10-10 08:00",
            "temp_c": 2.9,
            "temp_f": 37.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 325,
            "wind_dir": "NW",
            "pressure_mb": 1023,
            "pressure_in": 30.22,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 77,
            "cloud": 2,
            "feelslike_c": 1.8,
            "feelslike_f": 35.2,
            "windchill_c": 1.8,
            "windchill_f": 35.2,
            "heatindex_c": 2.9,
            "heatindex_f": 37.2,
            "dewpoint_c": -0.8,
            "dewpoint_f": 30.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.6,
            "gust_kph": 12.2,
            "uv": 2
          },
          {
            "time_epoch": 1665406800,
            "time": "2022-10-10 09:00",
            "temp_c": 3.4,
            "temp_f": 38.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 320,
            "wind_dir": "NW",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 63,
            "cloud": 0,
            "feelslike_c": 1.5,
            "feelslike_f": 34.7,
            "windchill_c": 1.5,
            "windchill_f": 34.7,
            "heatindex_c": 3.4,
            "heatindex_f": 38.1,
            "dewpoint_c": -2.9,
            "dewpoint_f": 26.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.4,
            "gust_kph": 8.6,
            "uv": 2
          },
          {
            "time_epoch": 1665410400,
            "time": "2022-10-10 10:00",
            "temp_c": 5.6,
            "temp_f": 42.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 308,
            "wind_dir": "NW",
            "pressure_mb": 1024,
            "pressure_in": 30.24,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 56,
            "cloud": 0,
            "feelslike_c": 4,
            "feelslike_f": 39.2,
            "windchill_c": 4,
            "windchill_f": 39.2,
            "heatindex_c": 5.6,
            "heatindex_f": 42.1,
            "dewpoint_c": -2.5,
            "dewpoint_f": 27.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.4,
            "gust_kph": 8.6,
            "uv": 3
          },
          {
            "time_epoch": 1665414000,
            "time": "2022-10-10 11:00",
            "temp_c": 8,
            "temp_f": 46.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.6,
            "wind_kph": 9,
            "wind_degree": 290,
            "wind_dir": "WNW",
            "pressure_mb": 1024,
            "pressure_in": 30.24,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 44,
            "cloud": 0,
            "feelslike_c": 5.8,
            "feelslike_f": 42.4,
            "windchill_c": 5.8,
            "windchill_f": 42.4,
            "heatindex_c": 8,
            "heatindex_f": 46.4,
            "dewpoint_c": -3.5,
            "dewpoint_f": 25.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.5,
            "gust_kph": 10.4,
            "uv": 3
          },
          {
            "time_epoch": 1665417600,
            "time": "2022-10-10 12:00",
            "temp_c": 9.3,
            "temp_f": 48.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 280,
            "wind_dir": "W",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 48,
            "cloud": 0,
            "feelslike_c": 7.7,
            "feelslike_f": 45.9,
            "windchill_c": 7.7,
            "windchill_f": 45.9,
            "heatindex_c": 9.3,
            "heatindex_f": 48.7,
            "dewpoint_c": -1.2,
            "dewpoint_f": 29.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.4,
            "gust_kph": 11.9,
            "uv": 3
          },
          {
            "time_epoch": 1665421200,
            "time": "2022-10-10 13:00",
            "temp_c": 10.1,
            "temp_f": 50.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 274,
            "wind_dir": "W",
            "pressure_mb": 1024,
            "pressure_in": 30.22,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 44,
            "cloud": 3,
            "feelslike_c": 8.5,
            "feelslike_f": 47.3,
            "windchill_c": 8.5,
            "windchill_f": 47.3,
            "heatindex_c": 10.1,
            "heatindex_f": 50.2,
            "dewpoint_c": -1.5,
            "dewpoint_f": 29.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.3,
            "gust_kph": 13.3,
            "uv": 4
          },
          {
            "time_epoch": 1665424800,
            "time": "2022-10-10 14:00",
            "temp_c": 12.7,
            "temp_f": 54.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 273,
            "wind_dir": "W",
            "pressure_mb": 1023,
            "pressure_in": 30.21,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 41,
            "cloud": 0,
            "feelslike_c": 11.3,
            "feelslike_f": 52.3,
            "windchill_c": 11.3,
            "windchill_f": 52.3,
            "heatindex_c": 12.7,
            "heatindex_f": 54.9,
            "dewpoint_c": -0.3,
            "dewpoint_f": 31.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.8,
            "gust_kph": 15.8,
            "uv": 4
          },
          {
            "time_epoch": 1665428400,
            "time": "2022-10-10 15:00",
            "temp_c": 12.4,
            "temp_f": 54.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 275,
            "wind_dir": "W",
            "pressure_mb": 1023,
            "pressure_in": 30.19,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 41,
            "cloud": 9,
            "feelslike_c": 10.9,
            "feelslike_f": 51.6,
            "windchill_c": 10.9,
            "windchill_f": 51.6,
            "heatindex_c": 12.4,
            "heatindex_f": 54.3,
            "dewpoint_c": -0.6,
            "dewpoint_f": 30.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 4
          },
          {
            "time_epoch": 1665432000,
            "time": "2022-10-10 16:00",
            "temp_c": 12.5,
            "temp_f": 54.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 280,
            "wind_dir": "W",
            "pressure_mb": 1022,
            "pressure_in": 30.19,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 41,
            "cloud": 9,
            "feelslike_c": 11.1,
            "feelslike_f": 52,
            "windchill_c": 11.1,
            "windchill_f": 52,
            "heatindex_c": 12.5,
            "heatindex_f": 54.5,
            "dewpoint_c": -0.5,
            "dewpoint_f": 31.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.8,
            "gust_kph": 15.8,
            "uv": 4
          },
          {
            "time_epoch": 1665435600,
            "time": "2022-10-10 17:00",
            "temp_c": 12.4,
            "temp_f": 54.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 293,
            "wind_dir": "WNW",
            "pressure_mb": 1022,
            "pressure_in": 30.19,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 44,
            "cloud": 0,
            "feelslike_c": 11,
            "feelslike_f": 51.8,
            "windchill_c": 11,
            "windchill_f": 51.8,
            "heatindex_c": 12.4,
            "heatindex_f": 54.3,
            "dewpoint_c": 0.4,
            "dewpoint_f": 32.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.5,
            "gust_kph": 13.7,
            "uv": 4
          },
          {
            "time_epoch": 1665439200,
            "time": "2022-10-10 18:00",
            "temp_c": 8.4,
            "temp_f": 47.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 339,
            "wind_dir": "NNW",
            "pressure_mb": 1022,
            "pressure_in": 30.19,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 55,
            "cloud": 20,
            "feelslike_c": 7.9,
            "feelslike_f": 46.2,
            "windchill_c": 7.9,
            "windchill_f": 46.2,
            "heatindex_c": 8.4,
            "heatindex_f": 47.1,
            "dewpoint_c": -0.2,
            "dewpoint_f": 31.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.8,
            "gust_kph": 9.4,
            "uv": 3
          },
          {
            "time_epoch": 1665442800,
            "time": "2022-10-10 19:00",
            "temp_c": 6.4,
            "temp_f": 43.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2,
            "wind_kph": 3.2,
            "wind_degree": 27,
            "wind_dir": "NNE",
            "pressure_mb": 1023,
            "pressure_in": 30.2,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 58,
            "cloud": 25,
            "feelslike_c": 6.4,
            "feelslike_f": 43.5,
            "windchill_c": 6.4,
            "windchill_f": 43.5,
            "heatindex_c": 6.4,
            "heatindex_f": 43.5,
            "dewpoint_c": -1.2,
            "dewpoint_f": 29.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.3,
            "gust_kph": 6.8,
            "uv": 1
          },
          {
            "time_epoch": 1665446400,
            "time": "2022-10-10 20:00",
            "temp_c": 7.1,
            "temp_f": 44.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.6,
            "wind_kph": 2.5,
            "wind_degree": 97,
            "wind_dir": "E",
            "pressure_mb": 1023,
            "pressure_in": 30.21,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 57,
            "cloud": 0,
            "feelslike_c": 6.5,
            "feelslike_f": 43.7,
            "windchill_c": 6.5,
            "windchill_f": 43.7,
            "heatindex_c": 7.1,
            "heatindex_f": 44.8,
            "dewpoint_c": -0.8,
            "dewpoint_f": 30.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.4,
            "gust_kph": 5.4,
            "uv": 1
          },
          {
            "time_epoch": 1665450000,
            "time": "2022-10-10 21:00",
            "temp_c": 4.3,
            "temp_f": 39.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.8,
            "wind_kph": 2.9,
            "wind_degree": 158,
            "wind_dir": "SSE",
            "pressure_mb": 1024,
            "pressure_in": 30.22,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 62,
            "cloud": 17,
            "feelslike_c": 4.3,
            "feelslike_f": 39.7,
            "windchill_c": 4.3,
            "windchill_f": 39.7,
            "heatindex_c": 4.3,
            "heatindex_f": 39.7,
            "dewpoint_c": -2.2,
            "dewpoint_f": 28,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.8,
            "gust_kph": 6.1,
            "uv": 1
          },
          {
            "time_epoch": 1665453600,
            "time": "2022-10-10 22:00",
            "temp_c": 3.7,
            "temp_f": 38.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 176,
            "wind_dir": "S",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 65,
            "cloud": 11,
            "feelslike_c": 3.3,
            "feelslike_f": 37.9,
            "windchill_c": 3.3,
            "windchill_f": 37.9,
            "heatindex_c": 3.7,
            "heatindex_f": 38.7,
            "dewpoint_c": -2.2,
            "dewpoint_f": 28,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 4.7,
            "gust_kph": 7.6,
            "uv": 1
          },
          {
            "time_epoch": 1665457200,
            "time": "2022-10-10 23:00",
            "temp_c": 4.9,
            "temp_f": 40.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.8,
            "wind_kph": 2.9,
            "wind_degree": 180,
            "wind_dir": "S",
            "pressure_mb": 1023,
            "pressure_in": 30.2,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 69,
            "cloud": 0,
            "feelslike_c": 3.5,
            "feelslike_f": 38.3,
            "windchill_c": 3.5,
            "windchill_f": 38.3,
            "heatindex_c": 4.9,
            "heatindex_f": 40.8,
            "dewpoint_c": -0.3,
            "dewpoint_f": 31.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.8,
            "gust_kph": 6.1,
            "uv": 1
          }
        ]
      },
      {
        "date": "2022-10-11",
        "date_epoch": 1665446400,
        "day": {
          "maxtemp_c": 19.8,
          "maxtemp_f": 67.6,
          "mintemp_c": 1.3,
          "mintemp_f": 34.3,
          "avgtemp_c": 9.1,
          "avgtemp_f": 48.4,
          "maxwind_mph": 8.7,
          "maxwind_kph": 14,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 67,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 3
        },
        "astro": {
          "sunrise": "07:14 AM",
          "sunset": "06:24 PM",
          "moonrise": "07:20 PM",
          "moonset": "09:07 AM",
          "moon_phase": "Full Moon",
          "moon_illumination": "100"
        },
        "hour": [
          {
            "time_epoch": 1665460800,
            "time": "2022-10-11 00:00",
            "temp_c": 2.7,
            "temp_f": 36.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 1.8,
            "wind_kph": 2.9,
            "wind_degree": 207,
            "wind_dir": "SSW",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 69,
            "cloud": 15,
            "feelslike_c": 2.7,
            "feelslike_f": 36.9,
            "windchill_c": 2.7,
            "windchill_f": 36.9,
            "heatindex_c": 2.7,
            "heatindex_f": 36.9,
            "dewpoint_c": -2.4,
            "dewpoint_f": 27.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 3.8,
            "gust_kph": 6.1,
            "uv": 1
          },
          {
            "time_epoch": 1665464400,
            "time": "2022-10-11 01:00",
            "temp_c": 2.4,
            "temp_f": 36.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 227,
            "wind_dir": "SW",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 10,
            "feelslike_c": 1.6,
            "feelslike_f": 34.9,
            "windchill_c": 1.6,
            "windchill_f": 34.9,
            "heatindex_c": 2.4,
            "heatindex_f": 36.3,
            "dewpoint_c": -2.3,
            "dewpoint_f": 27.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.1,
            "gust_kph": 8.3,
            "uv": 1
          },
          {
            "time_epoch": 1665468000,
            "time": "2022-10-11 02:00",
            "temp_c": 3.6,
            "temp_f": 38.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 2.7,
            "wind_kph": 4.3,
            "wind_degree": 248,
            "wind_dir": "WSW",
            "pressure_mb": 1022,
            "pressure_in": 30.19,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 73,
            "cloud": 5,
            "feelslike_c": 1.5,
            "feelslike_f": 34.7,
            "windchill_c": 1.5,
            "windchill_f": 34.7,
            "heatindex_c": 3.6,
            "heatindex_f": 38.5,
            "dewpoint_c": -0.8,
            "dewpoint_f": 30.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 1
          },
          {
            "time_epoch": 1665471600,
            "time": "2022-10-11 03:00",
            "temp_c": 2.2,
            "temp_f": 36,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 235,
            "wind_dir": "SW",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 72,
            "cloud": 10,
            "feelslike_c": 0.6,
            "feelslike_f": 33.1,
            "windchill_c": 0.6,
            "windchill_f": 33.1,
            "heatindex_c": 2.2,
            "heatindex_f": 36,
            "dewpoint_c": -2.2,
            "dewpoint_f": 28,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.6,
            "gust_kph": 12.2,
            "uv": 1
          },
          {
            "time_epoch": 1665475200,
            "time": "2022-10-11 04:00",
            "temp_c": 2.3,
            "temp_f": 36.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 239,
            "wind_dir": "WSW",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 72,
            "cloud": 10,
            "feelslike_c": 0.3,
            "feelslike_f": 32.5,
            "windchill_c": 0.3,
            "windchill_f": 32.5,
            "heatindex_c": 2.3,
            "heatindex_f": 36.1,
            "dewpoint_c": -2.2,
            "dewpoint_f": 28,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.9,
            "gust_kph": 14.4,
            "uv": 1
          },
          {
            "time_epoch": 1665478800,
            "time": "2022-10-11 05:00",
            "temp_c": 3.1,
            "temp_f": 37.6,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 251,
            "wind_dir": "WSW",
            "pressure_mb": 1022,
            "pressure_in": 30.18,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 75,
            "cloud": 0,
            "feelslike_c": 1,
            "feelslike_f": 33.8,
            "windchill_c": 1,
            "windchill_f": 33.8,
            "heatindex_c": 3.1,
            "heatindex_f": 37.6,
            "dewpoint_c": -0.8,
            "dewpoint_f": 30.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.9,
            "gust_kph": 14.4,
            "uv": 1
          },
          {
            "time_epoch": 1665482400,
            "time": "2022-10-11 06:00",
            "temp_c": 1.6,
            "temp_f": 34.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 258,
            "wind_dir": "WSW",
            "pressure_mb": 1024,
            "pressure_in": 30.25,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 77,
            "cloud": 3,
            "feelslike_c": -0.5,
            "feelslike_f": 31.1,
            "windchill_c": -0.5,
            "windchill_f": 31.1,
            "heatindex_c": 1.6,
            "heatindex_f": 34.9,
            "dewpoint_c": -2,
            "dewpoint_f": 28.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.9,
            "gust_kph": 14.4,
            "uv": 1
          },
          {
            "time_epoch": 1665486000,
            "time": "2022-10-11 07:00",
            "temp_c": 1.3,
            "temp_f": 34.3,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 251,
            "wind_dir": "WSW",
            "pressure_mb": 1025,
            "pressure_in": 30.25,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 80,
            "cloud": 6,
            "feelslike_c": -0.7,
            "feelslike_f": 30.7,
            "windchill_c": -0.7,
            "windchill_f": 30.7,
            "heatindex_c": 1.3,
            "heatindex_f": 34.3,
            "dewpoint_c": -1.7,
            "dewpoint_f": 28.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.5,
            "gust_kph": 13.7,
            "uv": 1
          },
          {
            "time_epoch": 1665489600,
            "time": "2022-10-11 08:00",
            "temp_c": 3.2,
            "temp_f": 37.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 249,
            "wind_dir": "WSW",
            "pressure_mb": 1022,
            "pressure_in": 30.19,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 77,
            "cloud": 2,
            "feelslike_c": 0.8,
            "feelslike_f": 33.4,
            "windchill_c": 0.8,
            "windchill_f": 33.4,
            "heatindex_c": 3.2,
            "heatindex_f": 37.8,
            "dewpoint_c": -0.4,
            "dewpoint_f": 31.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.8,
            "gust_kph": 12.6,
            "uv": 2
          },
          {
            "time_epoch": 1665493200,
            "time": "2022-10-11 09:00",
            "temp_c": 5.7,
            "temp_f": 42.3,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 252,
            "wind_dir": "WSW",
            "pressure_mb": 1025,
            "pressure_in": 30.26,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 67,
            "cloud": 39,
            "feelslike_c": 4.1,
            "feelslike_f": 39.4,
            "windchill_c": 4.1,
            "windchill_f": 39.4,
            "heatindex_c": 5.7,
            "heatindex_f": 42.3,
            "dewpoint_c": 0,
            "dewpoint_f": 32,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 3
          },
          {
            "time_epoch": 1665496800,
            "time": "2022-10-11 10:00",
            "temp_c": 8.6,
            "temp_f": 47.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 259,
            "wind_dir": "W",
            "pressure_mb": 1025,
            "pressure_in": 30.26,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 59,
            "cloud": 7,
            "feelslike_c": 7.4,
            "feelslike_f": 45.3,
            "windchill_c": 7.4,
            "windchill_f": 45.3,
            "heatindex_c": 8.6,
            "heatindex_f": 47.5,
            "dewpoint_c": 1.1,
            "dewpoint_f": 34,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.6,
            "gust_kph": 9,
            "uv": 3
          },
          {
            "time_epoch": 1665500400,
            "time": "2022-10-11 11:00",
            "temp_c": 13.7,
            "temp_f": 56.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 243,
            "wind_dir": "WSW",
            "pressure_mb": 1022,
            "pressure_in": 30.17,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 60,
            "cloud": 0,
            "feelslike_c": 12.4,
            "feelslike_f": 54.3,
            "windchill_c": 12.4,
            "windchill_f": 54.3,
            "heatindex_c": 13.7,
            "heatindex_f": 56.7,
            "dewpoint_c": 6.1,
            "dewpoint_f": 43,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.8,
            "gust_kph": 9.4,
            "uv": 4
          },
          {
            "time_epoch": 1665504000,
            "time": "2022-10-11 12:00",
            "temp_c": 13.4,
            "temp_f": 56.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 226,
            "wind_dir": "SW",
            "pressure_mb": 1024,
            "pressure_in": 30.23,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 49,
            "cloud": 6,
            "feelslike_c": 12.8,
            "feelslike_f": 55,
            "windchill_c": 12.8,
            "windchill_f": 55,
            "heatindex_c": 13.4,
            "heatindex_f": 56.1,
            "dewpoint_c": 3.1,
            "dewpoint_f": 37.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 4
          },
          {
            "time_epoch": 1665507600,
            "time": "2022-10-11 13:00",
            "temp_c": 15,
            "temp_f": 59,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 221,
            "wind_dir": "SW",
            "pressure_mb": 1023,
            "pressure_in": 30.2,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 46,
            "cloud": 6,
            "feelslike_c": 14.4,
            "feelslike_f": 57.9,
            "windchill_c": 14.4,
            "windchill_f": 57.9,
            "heatindex_c": 15,
            "heatindex_f": 59,
            "dewpoint_c": 3.5,
            "dewpoint_f": 38.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.5,
            "gust_kph": 13.7,
            "uv": 5
          },
          {
            "time_epoch": 1665511200,
            "time": "2022-10-11 14:00",
            "temp_c": 17.8,
            "temp_f": 64,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 221,
            "wind_dir": "SW",
            "pressure_mb": 1021,
            "pressure_in": 30.14,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 49,
            "cloud": 0,
            "feelslike_c": 17.8,
            "feelslike_f": 64,
            "windchill_c": 17.8,
            "windchill_f": 64,
            "heatindex_c": 17.8,
            "heatindex_f": 64,
            "dewpoint_c": 6.9,
            "dewpoint_f": 44.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 5
          },
          {
            "time_epoch": 1665514800,
            "time": "2022-10-11 15:00",
            "temp_c": 19.6,
            "temp_f": 67.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 222,
            "wind_dir": "SW",
            "pressure_mb": 1021,
            "pressure_in": 30.14,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 43,
            "cloud": 6,
            "feelslike_c": 19.6,
            "feelslike_f": 67.3,
            "windchill_c": 19.6,
            "windchill_f": 67.3,
            "heatindex_c": 19.6,
            "heatindex_f": 67.3,
            "dewpoint_c": 6.8,
            "dewpoint_f": 44.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.8,
            "gust_kph": 15.8,
            "uv": 5
          },
          {
            "time_epoch": 1665518400,
            "time": "2022-10-11 16:00",
            "temp_c": 19.8,
            "temp_f": 67.6,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.7,
            "wind_kph": 14,
            "wind_degree": 223,
            "wind_dir": "SW",
            "pressure_mb": 1020,
            "pressure_in": 30.13,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 45,
            "cloud": 8,
            "feelslike_c": 19.8,
            "feelslike_f": 67.6,
            "windchill_c": 19.8,
            "windchill_f": 67.6,
            "heatindex_c": 19.8,
            "heatindex_f": 67.6,
            "dewpoint_c": 7.5,
            "dewpoint_f": 45.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.1,
            "gust_kph": 16.2,
            "uv": 5
          },
          {
            "time_epoch": 1665522000,
            "time": "2022-10-11 17:00",
            "temp_c": 18.2,
            "temp_f": 64.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 216,
            "wind_dir": "SW",
            "pressure_mb": 1019,
            "pressure_in": 30.1,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 52,
            "cloud": 0,
            "feelslike_c": 18.2,
            "feelslike_f": 64.8,
            "windchill_c": 18.2,
            "windchill_f": 64.8,
            "heatindex_c": 18.2,
            "heatindex_f": 64.8,
            "dewpoint_c": 8.2,
            "dewpoint_f": 46.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.5,
            "gust_kph": 16.9,
            "uv": 5
          },
          {
            "time_epoch": 1665525600,
            "time": "2022-10-11 18:00",
            "temp_c": 14.3,
            "temp_f": 57.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 5.6,
            "wind_kph": 9,
            "wind_degree": 197,
            "wind_dir": "SSW",
            "pressure_mb": 1020,
            "pressure_in": 30.11,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 65,
            "cloud": 5,
            "feelslike_c": 13.9,
            "feelslike_f": 57,
            "windchill_c": 13.9,
            "windchill_f": 57,
            "heatindex_c": 14.3,
            "heatindex_f": 57.7,
            "dewpoint_c": 7.9,
            "dewpoint_f": 46.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.6,
            "gust_kph": 18.7,
            "uv": 4
          },
          {
            "time_epoch": 1665529200,
            "time": "2022-10-11 19:00",
            "temp_c": 11.5,
            "temp_f": 52.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 181,
            "wind_dir": "S",
            "pressure_mb": 1020,
            "pressure_in": 30.13,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 76,
            "cloud": 5,
            "feelslike_c": 10.4,
            "feelslike_f": 50.7,
            "windchill_c": 10.4,
            "windchill_f": 50.7,
            "heatindex_c": 11.5,
            "heatindex_f": 52.7,
            "dewpoint_c": 7.5,
            "dewpoint_f": 45.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.2,
            "gust_kph": 21.2,
            "uv": 1
          },
          {
            "time_epoch": 1665532800,
            "time": "2022-10-11 20:00",
            "temp_c": 11.6,
            "temp_f": 52.9,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 195,
            "wind_dir": "SSW",
            "pressure_mb": 1020,
            "pressure_in": 30.11,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 68,
            "cloud": 0,
            "feelslike_c": 10.8,
            "feelslike_f": 51.4,
            "windchill_c": 10.8,
            "windchill_f": 51.4,
            "heatindex_c": 11.6,
            "heatindex_f": 52.9,
            "dewpoint_c": 5.9,
            "dewpoint_f": 42.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.3,
            "gust_kph": 19.8,
            "uv": 1
          },
          {
            "time_epoch": 1665536400,
            "time": "2022-10-11 21:00",
            "temp_c": 9,
            "temp_f": 48.2,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 209,
            "wind_dir": "SSW",
            "pressure_mb": 1021,
            "pressure_in": 30.14,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 87,
            "cloud": 0,
            "feelslike_c": 7.7,
            "feelslike_f": 45.9,
            "windchill_c": 7.7,
            "windchill_f": 45.9,
            "heatindex_c": 9,
            "heatindex_f": 48.2,
            "dewpoint_c": 6.9,
            "dewpoint_f": 44.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.2,
            "gust_kph": 18,
            "uv": 1
          },
          {
            "time_epoch": 1665540000,
            "time": "2022-10-11 22:00",
            "temp_c": 8.6,
            "temp_f": 47.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 219,
            "wind_dir": "SW",
            "pressure_mb": 1021,
            "pressure_in": 30.15,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 88,
            "cloud": 3,
            "feelslike_c": 7.3,
            "feelslike_f": 45.1,
            "windchill_c": 7.3,
            "windchill_f": 45.1,
            "heatindex_c": 8.6,
            "heatindex_f": 47.5,
            "dewpoint_c": 6.8,
            "dewpoint_f": 44.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.7,
            "gust_kph": 17.3,
            "uv": 1
          },
          {
            "time_epoch": 1665543600,
            "time": "2022-10-11 23:00",
            "temp_c": 8.9,
            "temp_f": 48,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 222,
            "wind_dir": "SW",
            "pressure_mb": 1020,
            "pressure_in": 30.11,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 79,
            "cloud": 0,
            "feelslike_c": 7.8,
            "feelslike_f": 46,
            "windchill_c": 7.8,
            "windchill_f": 46,
            "heatindex_c": 8.9,
            "heatindex_f": 48,
            "dewpoint_c": 5.4,
            "dewpoint_f": 41.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.4,
            "gust_kph": 15.1,
            "uv": 1
          }
        ]
      }
    ]
  }
}

export default SAMPLE